#!/bin/bash
echo "============================================="
echo " Lab Setup — Q19: Break Root Password"
echo "============================================="
echo ""
echo "This task requires PHYSICAL/CONSOLE access to servera."
echo "You cannot perform this task via SSH."
echo ""
echo "Steps to access the GRUB menu:"
echo "  1. Open the console for servera"
echo "  2. Reboot the system (or send Ctrl+Alt+Del)"
echo "  3. When GRUB menu appears, press a key to stop the timer"
echo "  4. Press 'e' to edit the boot entry"
echo ""
echo "Lab setup complete. Read Questions.bash for the task."
