#!/bin/bash
# Lab Setup for Question 1: Configure the Network
echo "============================================="
echo " Lab Setup — Q1: Configure the Network"
echo "============================================="
echo ""
echo "This question requires manual network configuration."
echo "No automated setup is needed."
echo ""
echo "Prerequisites:"
echo "  - You should be logged into serverb"
echo "  - The system should have a network interface available"
echo ""
echo "Verify your current network settings:"
echo "  hostname"
echo "  nmcli con show"
echo "  ip addr show"
echo ""
echo "Lab setup complete. Read Questions.bash for the task."
